services:
  semaphore:
    ports:
      - ${PORT}:3000
    image: semaphoreui/semaphore:v2.16.18
    restart: unless-stopped
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: $SEMAPHORE_ADMIN_PASSWORD
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_RUNNER_REGISTRATION_TOKEN: ${SEMAPHORE_RUNNER_REGISTRATION_TOKEN}
      SEMAPHORE_USE_REMOTE_RUNNER: "true"
    volumes:
      - ./semaphore_data:/var/lib/semaphore
      - ./semaphore_config:/etc/semaphore

  semaphore-runner:
    image: semaphoreui/runner:v2.16.18
    restart: unless-stopped
    environment:
      SEMAPHORE_WEB_ROOT: http://semaphore:3000
      SEMAPHORE_RUNNER_REGISTRATION_TOKEN: ${SEMAPHORE_RUNNER_REGISTRATION_TOKEN}
    volumes:
      - ./runner_data:/var/lib/semaphore
      - ./runner_config:/etc/semaphore
    depends_on:
      - semaphore